apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm/app/
    repoURL: https://github.com/punkerside/awsday-demo
    targetRevision: HEAD
    helm:
      parameters:
        - name: 'name'
          value: $NAME
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true