apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
  labels:
    code: yaml
    trigger: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/punkerside/argocd-demo
      path: manifest/helm/cluster
      targetRevision: HEAD
      helm:
        parameters:
          - name: 'name'
            value: $NAME
          - name: 'version'
            value: $VERSION
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true