apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie
  namespace: argocd
  labels:
    runtime: python
    tool: kustomize
    trigger: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifest/kubectl/app
    repoURL: https://github.com/punkerside/argocd-demo
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true