kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - name: http
    port: 80
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: redis-slave
  labels:
    app: redis
    role: replica
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: replica