kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "elb-cert"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name="elb-name"
    service.beta.kubernetes.io/aws-load-balancer-name: "elb-name"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - name: http
    port: 80
    targetPort: http-server
  - name: https
    port: 443
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer