apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  namespace: {{ .Values.namespace }}
  labels:
    app: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
      - name: movie
        image: 509472714099.dkr.ecr.us-east-1.amazonaws.com/awsday-lab-gitops:python
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - name: redis
        image: redis:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 200m
            memory: 1024Mi
          limits:
            cpu: 200m
            memory: 1024Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music
  namespace: {{ .Values.namespace }}
  labels:
    app: music
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: music
        image: 509472714099.dkr.ecr.us-east-1.amazonaws.com/awsday-lab-gitops:go
        imagePullPolicy: Always
        ports:
        - containerPort: 9081
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - name: mongo
        image: mongo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 200m
            memory: 1024Mi
          limits:
            cpu: 200m
            memory: 1024Mi