kind: ReplicationController
apiVersion: v1
metadata:
  name: guestbook
  namespace: {{ .Values.namespace }}
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: registry.k8s.io/guestbook:v3
        ports:
        - name: http-server
          containerPort: 3000
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-master
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    app: redis
    role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: registry.k8s.io/redis:e2e
        ports:
        - name: redis-server
          containerPort: 6379
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: redis-replica
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    role: replica
spec:
  replicas: 2
  selector:
    app: redis
    role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
      - name: redis-replica
        image: registry.k8s.io/redis-slave:v2
        ports:
        - name: redis-server
          containerPort: 6379